name: msaratwasel_services
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+5

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_local_notifications: ^17.2.2

  # Networking
  dio: ^5.7.0
  web_socket_channel: ^2.4.0

  # State Management
  flutter_bloc: ^8.1.6

  # Functional Programming
  dartz: ^0.10.1

  # Value Equality
  equatable: ^2.0.5

  # Local Storage
  shared_preferences: ^2.3.3

  # DI
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  # Navigation
  go_router: ^14.6.0

  # UI Enhancements
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  phosphor_flutter: ^2.1.0
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.12.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  table_calendar: ^3.2.0
  permission_handler: ^11.3.1

  # Camera & Maps
  mobile_scanner: ^7.2.0
  video_compress: ^3.1.4
  google_mlkit_barcode_scanning: ^0.14.2
  google_maps_flutter: ^2.17.0
  google_directions_api: ^0.10.0
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.1.0
  widget_to_marker: ^1.0.6
  camerawesome: ^2.5.0

  # Firebase
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  flutter_background_service: ^5.1.0
  device_info_plus: ^12.4.0
  http: ^1.6.0
  audioplayers: ^6.6.0
  layout: ^1.0.5
  responsive_builder: ^0.7.1
  responsive_framework: ^1.5.1
  platform: ^3.1.6
  connectivity_plus: 7.0.0

  # Added packages requested by user
  get: ^4.6.1
  
  # DateTime
  jiffy: any
  
  # Images
  cached_network_image: ^3.2.0 
  image_pickers: ^2.0.0+2
  
  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  
  # Google Map
  geocoding: ^2.0.4
  
  # Firebase And Notification 
  cloud_firestore: any
  
  # Local Data Cache
  sqflite: ^2.0.2
  path: ^1.8.0
  
  # Qrcode 
  qr_flutter: ^4.0.0
  
  # Lists, Dropdowns, Badges
  grouped_list: ^4.2.0
  dropdown_search: ^3.0.1
  badges: ^2.0.2
  
  # Icon 
  fluttericon: ^2.0.0
  
  # Auth & Utils
  google_sign_in: ^5.3.1  
  device_preview: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.11.0
  injectable_generator: ^2.12.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/msarticon/
    - assets/sounds/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/Google_Sans/static/GoogleSans-Regular.ttf
        - asset: assets/fonts/Google_Sans/static/GoogleSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Google_Sans/static/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Google_Sans/static/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Google_Sans/static/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Google_Sans/static/GoogleSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Google_Sans/static/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Google_Sans/static/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon 4.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon 4.png"

dependency_overrides:
  sqflite_android: 2.4.1
